version: '3.8'
services:
  backend:
    build: ./ApiBackendDia
    ports:
      - "8091:8080"
    env_file:
      - ./ApiBackendDia/my-go-project/.env  
  frontend:
    build: ./ApiFrontendDia
    ports:
      - "80:80"
    depends_on:
      - backend

  proxy-backend:
    build: ./proxy-backend
    ports:
      - "3001:3001"
    restart: unless-stopped      